name: Step05 - Install ML Deps

on:
  workflow_dispatch:
    inputs:
      app_user:
        description: 'VM user para instalar dependencias'
        required: false
        default: 'azureuser'

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  RESOURCE_GROUP: rg-cftec-m62025-SINT646
  VM_NAME: vm-cftec-m62025-SINT646-labs

jobs:
  install-ml-deps:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure CLI Login (Service Principal)
        shell: bash
        run: |
          set -euo pipefail
          az login --service-principal \
            --username "$ARM_CLIENT_ID" \
            --password "$ARM_CLIENT_SECRET" \
            --tenant "$ARM_TENANT_ID"
          az account set --subscription "$ARM_SUBSCRIPTION_ID"

      - name: Run install script on VM (ML deps)
        shell: bash
        run: |
          set -euo pipefail
          az vm run-command invoke \
            --resource-group "$RESOURCE_GROUP" \
            --name "$VM_NAME" \
            --command-id RunShellScript \
            --scripts @"$GITHUB_WORKSPACE/scripts/install_ml_deps.sh" \
            --parameters "${{ inputs.app_user }}" \
            --query "value[0].message" -o tsv

      - name: Run install script on VM (Jupyter widgets)
        shell: bash
        run: |
          set -euo pipefail
          az vm run-command invoke \
            --resource-group "$RESOURCE_GROUP" \
            --name "$VM_NAME" \
            --command-id RunShellScript \
            --scripts @"$GITHUB_WORKSPACE/scripts/install_jupyter_widgets.sh" \
            --parameters "${{ inputs.app_user }}" \
            --query "value[0].message" -o tsv

      - name: Verify packages installed
        shell: bash
        run: |
          set -euo pipefail
          az vm run-command invoke \
            --resource-group "$RESOURCE_GROUP" \
            --name "$VM_NAME" \
            --command-id RunShellScript \
            --scripts "su - '${{ inputs.app_user }}' -c 'python3 -m pip show torch transformers pymongo mysql-connector-python ipywidgets widgetsnbextension | egrep \"Name:|Version:\" || true'" \
            --query "value[0].message" -o tsv

      - name: Verify nbextensions
        shell: bash
        run: |
          set -euo pipefail
          az vm run-command invoke \
            --resource-group "$RESOURCE_GROUP" \
            --name "$VM_NAME" \
            --command-id RunShellScript \
            --scripts "su - '${{ inputs.app_user }}' -c 'jupyter nbextension list || true'" \
            --query "value[0].message" -o tsv
