name: Step11 - Setup Metabase (public IP, DB + charts + dashboard)

on:
  workflow_dispatch:
    inputs:
      admin_email:
        description: 'Correo admin Metabase'
        required: false
        default: 'admin@example.com'
      db_display_name:
        description: 'Nombre logico de la DB en Metabase (sin espacios)'
        required: false
        default: 'DWH'
      admin_pass:
        description: 'Password admin Metabase (opcional; si vacio usa "pass" para demo)'
        required: false
        default: 'Seguro@123456789'

permissions:
  id-token: write
  contents: read

concurrency:
  group: vm-cftec-m62025-SINT646-labs
  cancel-in-progress: false

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  RESOURCE_GROUP: rg-cftec-m62025-SINT646
  VM_NAME: vm-cftec-m62025-SINT646-labs

jobs:
  setup-metabase-public:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure CLI Login (Service Principal)
        shell: bash
        run: |
          set -euo pipefail
          az login --service-principal \
            --username "$ARM_CLIENT_ID" \
            --password "$ARM_CLIENT_SECRET" \
            --tenant "$ARM_TENANT_ID"
          az account set --subscription "$ARM_SUBSCRIPTION_ID"

      - name: Get VM public IP
        id: getpip
        shell: bash
        run: |
          set -euo pipefail
          PUBIP="$(az vm list-ip-addresses \
            -g "$RESOURCE_GROUP" -n "$VM_NAME" \
            --query "[0].virtualMachine.network.publicIpAddresses[0].ipAddress" -o tsv)"
          if [[ -z "${PUBIP:-}" ]]; then
            echo "No public IP found for $VM_NAME" >&2
            exit 1
          fi
          echo "pubip=${PUBIP}" >> "$GITHUB_OUTPUT"

      - name: Ensure mysql/metabase in same Docker network (labnet)
        shell: bash
        run: |
          set -euo pipefail
          az vm run-command invoke \
            --resource-group "$RESOURCE_GROUP" --name "$VM_NAME" \
            --command-id RunShellScript \
            --scripts '
              set -eu
              docker network create labnet >/dev/null 2>&1 || true
              for svc in mysql metabase; do
                if docker ps --format "{{.Names}}" | grep -qx "$svc"; then
                  if ! docker network inspect labnet -f "{{json .Containers}}" | grep -q "$svc"; then
                    docker network connect labnet "$svc" || true
                  fi
                fi
              done
              echo "labnet OK; mysql/metabase conectados si estaban corriendo."
            ' \
            --query "value[0].message" -o tsv

      - name: Wait for Metabase to be ready (local healthcheck)
        shell: bash
        run: |
          set -euo pipefail
          az vm run-command invoke \
            --resource-group "$RESOURCE_GROUP" --name "$VM_NAME" \
            --command-id RunShellScript \
            --scripts '
              set -eu
              timeout="${1:-240}"
              start="$(date +%s)"
              while :; do
                code="$(curl -sS -m 2 -o /dev/null -w "%{http_code}" http://127.0.0.1:3000/api/health || true)"
                if [ "$code" = "200" ]; then
                  echo "Metabase responde /api/health (200)."
                  exit 0
                fi
                now="$(date +%s)"
                elapsed=$((now - start))
                if [ "$elapsed" -ge "$timeout" ]; then
                  echo "Metabase no listo tras ${timeout}s" >&2
                  docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | egrep "metabase|^NAMES" || true
                  exit 1
                fi
                sleep 3
              done
            ' \
            --parameters "240" \
            --query "value[0].message" -o tsv

      - name: Resolve admin password (input or default)
        id: mbpass
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "${{ inputs.admin_pass }}" ]]; then
            echo "pass=${{ inputs.admin_pass }}" >> "$GITHUB_OUTPUT"
          else
            echo "pass=pass" >> "$GITHUB_OUTPUT"
          fi

      - name: Create MySQL user for Metabase (native auth)
        shell: bash
        run: |
          set -euo pipefail
          az vm run-command invoke \
            --resource-group "$RESOURCE_GROUP" --name "$VM_NAME" \
            --command-id RunShellScript \
            --scripts '
              set -eu
              docker exec -i mysql mysql -uroot -ppass <<SQL
CREATE USER IF NOT EXISTS '\''metabase'\''@'\''%'\'' IDENTIFIED WITH mysql_native_password BY '\''mb_pass_123'\'';
GRANT SELECT, SHOW VIEW ON lab.* TO '\''metabase'\''@'\''%'\'';
FLUSH PRIVILEGES;
SQL
              echo "MySQL: usuario metabase creado/actualizado (metabase/mb_pass_123, permisos read-only sobre lab.*)"
            ' \
            --query "value[0].message" -o tsv


      - name: Seed Metabase via API (runs on VM, local URL; args sin espacios)
        shell: bash
        run: |
          set -euo pipefail
          ADMIN_EMAIL="admin@example.com"
          ADMIN_NAME="Admin_User"
          MB_URL="http://127.0.0.1:3000"

          # credenciales MySQL para Metabase (usuario nativo)
          DB_HOST="mysql"; DB_PORT="3306"; DB_NAME="lab"; DB_USER="metabase"; DB_PASS="mb_pass_123"
          DB_DISPLAY="DWH"
          DASH_TITLE="Sentiment_Streaming_Kafka_Mongo_DL_MySQL"

          # password robusto para Metabase (o usa tu Secret)
          MB_PASS="$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 16)"

          az vm run-command invoke \
            --resource-group "$RESOURCE_GROUP" \
            --name "$VM_NAME" \
            --command-id RunShellScript \
            --scripts @"$GITHUB_WORKSPACE/scripts/setup_metabase_and_seed.sh" \
            --parameters \
              "$ADMIN_EMAIL" \
              "$MB_PASS" \
              "$ADMIN_NAME" \
              "$MB_URL" \
              "$DB_HOST" "$DB_PORT" "$DB_NAME" "$DB_USER" "$DB_PASS" \
              "$DB_DISPLAY" \
              "$DASH_TITLE" \
            --query "value[0].message" -o tsv

      - name: Show public access
        shell: bash
        run: |
          set -euo pipefail
          PUBIP="${{ steps.getpip.outputs.pubip }}"
          {
            echo "## Metabase configurado (acceso publico restringido por NSG)"
            echo
            echo "- URL:  http://${PUBIP}:3000"
            echo "- Admin: ${{ inputs.admin_email }}"
            echo "- Base de datos: '${{ inputs.db_display_name }}' -> host=mysql, puerto=3306, db=lab"
            echo
            echo "Notas:"
            echo "- El seed se realiza via http://127.0.0.1:3000 dentro de la VM; el acceso publico es via IP/NSG."
            echo "- mysql y metabase estan unidos a la red Docker 'labnet' para resolucion por nombre."
          } >> "$GITHUB_STEP_SUMMARY"
